{% set name = "itsdangerous" %}
{% set version = "2.1.2" %}
{% set hash = "5dbbc68b317e5e42f327f9021763545dc3fc3bfe22e6deb96aaf1fc38874156a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - python >=3.7

test:
  imports:
    - itsdangerous

about:
  home: https://github.com/pallets/itsdangerous
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Various helpers to pass trusted data to untrusted environments.
  doc_url: http://pythonhosted.org/itsdangerous
  dev_url: https://github.com/pallets/itsdangerous

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
    - williamjamir
